### ISSUE TITLE
Handle react 404 page not found error and display the 404 Page

### ISSUE THREAD

**Issue by trickster26** [trickster26/alpha_react#6]
If route is not present in routes and no component is assigned to that route display a component which will say this route is not present and it should be beasutiful

**Comment by amankumarsahani** [comment]
@trickster26  Done in branch random_url_page_breakdown. Kindly review and merge.

**Comment by trickster26** [comment]
Working but routes like admin/dashboard/abc or admin/fgh not working but i dont think this is important
